fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Prevent giant files from being committed
      - id: check-added-large-files
      # Forbid files which have a UTF-8 byte-order marker
      - id: check-byte-order-marker
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Ensures that (non-binary) executables have a shebang.
      - id: check-executables-have-shebangs
      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
      # Checks for symlinks which do not point to anything.
      - id: check-symlinks
      # This hook checks toml files for parseable syntax.
      - id: check-toml
      # This hook checks xml files for parseable syntax.
      - id: check-xml
      # This hook checks yaml files for parseable syntax.
      - id: check-yaml
        args: ["--unsafe"]
      # Detects the presence of private keys
      - id: detect-private-key
      # Makes sure files end in a newline and only a newline.
      - id: end-of-file-fixer
      # Sorts entries in requirements.txt.
      - id: requirements-txt-fixer
      # Sorts simple YAML files which consist only of top-level keys, preserving comments and blocks.
      - id: sort-simple-yaml
      # This hook trims trailing whitespace.
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --hook-config=--sort-by-required
          - --hook-config=--with-aggregate-type-defaults
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_checkov
